version: "3.8"
services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d file-manager-db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    environment:
        POSTGRES_DB: file-manager-db
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
        - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  file-manager-api:
    build: ./server
    command: npm start
    volumes:
      - ./server:/app
      - /app/
      - /app/uploads
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/file-manager-db
  file-manager-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - file-manager-api


volumes:
  db-data: